testing and debugging section
Defiance-Digital/projen pull request #13
Opened 2023-12-27 20:38 UTC by mikejgray

Adds a section on testing and debugging

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-29 15:44 UTC, mbonig requested changes

2023-12-29 15:44 UTC, mbonig commented on docusaurus/docs/testing/index.md
> +projen project, you can try removing your `README.md` file code and see if it still
please add an example of trying to remove a file.

2023-12-29 15:56 UTC, mikejgray commented on docusaurus/docs/testing/index.md
> +projen project, you can try removing your `README.md` file code and see if it still
I didn't add one because there are several ways someone might try doing it in their project, and I would assume if they did it they'd know where the code was...if you see value in it, though, I'll add an example of how it might be done

2023-12-29 16:22 UTC, mbonig requested changes

2023-12-29 16:26 UTC, mikejgray commented on docusaurus/docs/testing/index.md
> +const project = new CustomNodeProject({
Why is that misleading? `readme: false` in NodeProject will remove the sample README file

2023-12-29 17:29 UTC, mbonig requested changes

2023-12-29 17:29 UTC, mbonig commented on docusaurus/docs/testing/index.md
> +const project = new CustomNodeProject({
because the 'readme' property isn't guaranteed to exist.

2023-12-29 17:30 UTC, mikejgray commented on docusaurus/docs/testing/index.md
> +const project = new CustomNodeProject({
It is on anything subclassing github projects 😄

2024-01-02 16:14 UTC, mbonig approved these changes
:shipit:

2024-01-02 16:21 UTC, mikejgray commented
@mbonig Concerns about the failing build? Or merge it and we'll clean all that up before the upstream PR?

2024-01-03 14:59 UTC, mbonig commented
> @mbonig Concerns about the failing build? Or merge it and we'll clean all that up before the upstream PR?

please fix

2024-01-04 22:45 UTC, merged