feat: developing custom constructs
Defiance-Digital/projen pull request #5
Opened 2023-11-08 23:35 UTC by mikejgray

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-09 15:33 UTC, mbonig requested changes
All the content in here is good content, but none of it seems like a 'custom component' guide. 

I was expecting to see something covering the creating of a new class that inherited from Component and that generated content from a very low level. Then additional sections that talked about subclassing TextFile or other existing classes to create something unique that can be re-used in multiple projects. 

I don't think this content should go away, though. It's all very good, just need to go into different sections/pages.

2023-11-09 15:33 UTC, mbonig commented on docusaurus/docs/custom-constructs/index.md
> +## Starting with a base project
I'm confused on why the base project is needed. If this guide is about creating custom components, then I wouldn't expect to see anything about a new project type being created, since that's covered in the other guide.

I think this section and the next (Copying files to a project) aren't really part of creating a custom component.

2023-11-09 15:36 UTC, mikejgray commented
> All the content in here is good content, but none of it seems like a 'custom component' guide.
> 
> I was expecting to see something covering the creating of a new class that inherited from Component and that generated content from a very low level. Then additional sections that talked about subclassing TextFile or other existing classes to create something unique that can be re-used in multiple projects.
> 
> I don't think this content should go away, though. It's all very good, just need to go into different sections/pages.

Gotcha, I misunderstood the assignment! I'll move this to a different section and write the low-level documentation you're looking for. Thanks for the feedback!

2023-11-10 21:19 UTC, mbonig requested changes
Tons of great stuff here!

2023-11-10 21:19 UTC, mbonig commented on docusaurus/docs/custom/custom-projects.md
> +While it may not appropriate for the larger projen community to enforce
huh?

2023-11-10 21:19 UTC, mbonig commented on docusaurus/docs/custom/custom-projects.md
> +    new PullRequestTemplate(this.github!, {
One thing I'd recommend is we push for this sort of thing to go into its own construct. Right now the logic of what goes into the PR is baked into the MyProject class. If you had other classes and wanted similar PR templates, you'd have to copy/paste. Or, if there was a MyPullRequestTemplate class that baked it in there, it's more reusable.

2023-11-10 21:19 UTC, mbonig commented on docusaurus/docs/custom/custom-projects.md
> +:::warning
I'd actually go so far to say that this way of handling dependencies is wrong and that the second method you mention, where the dep is there but the version is an option, is the better approach.

2023-11-10 21:19 UTC, mbonig commented on docusaurus/docs/custom/custom-projects.md
> +const upgradeMain = project.tryFindObjectFile('.github/workflows/upgrade-main.yml');
This concerns me... it shouldn't be this hard to publish to github actions. Can we talk about why this is needed? I didn't think we needed this for Momnt's setup that published packages to GitHub.

2023-11-10 21:19 UTC, mbonig commented on docusaurus/docs/custom/custom-components.md
> +create a `.gitignore` file as a sample and then let teams manage them how they
This sort of thing could be covered in the custom-projects section and would be pretty helpful to document.

2023-11-10 21:19 UTC, mbonig commented on docusaurus/docs/custom/custom-components.md
> +      "# Security",
Could this content be handled through triple ticks too?

2023-11-10 21:19 UTC, mbonig commented on docusaurus/docs/custom/custom-components.md
> +    writeFile(fullFilename, contents, { readonly: false });
I think it'd be good if you included the import for this 'writeFile' at the top. Right now it's a little confusing on where this is coming from.

2023-11-14 02:43 UTC, mikejgray commented on docusaurus/docs/custom/custom-projects.md
> +[Be sure to include any files you want to copy to your project's `lib` folder.](#copying-files-to-a-project)
I moved the warning inside the tip that talks about doing this.

2023-11-14 02:54 UTC, mikejgray commented on docusaurus/docs/custom/custom-projects.md
> +const upgradeMain = project.tryFindObjectFile('.github/workflows/upgrade-main.yml');
Good callout - I think this was in earlier versions of projen but was fixed. I'll remove.

2023-11-14 02:57 UTC, mikejgray commented on docusaurus/docs/custom/custom-components.md
> +create a `.gitignore` file as a sample and then let teams manage them how they
It is covered - I have sections on creating unmanaged files and creating managed files. Is there something in there that is missing? Happy to fill in any gaps I've left.

2023-11-14 03:00 UTC, mikejgray commented on docusaurus/docs/custom/custom-components.md
> +      "# Security",
Template literals are single ticks, right?

2023-11-14 20:52 UTC, mbonig commented on docusaurus/docs/custom/custom-components.md
> +      "# Security",
duh, here I am with python on my brain. yes, backticks though.

2023-11-14 21:13 UTC, mbonig approved these changes

2023-11-21 17:14 UTC, merged